name: Foot Track Backend CI/CD

on:
  push:
    branches:
      [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Install dependencies
      run: dotnet restore
      working-directory: src/FootTrack.Api
      
    - name: Build with dotnet
      run: dotnet build --configuration Release --no-restore
      working-directory: src/FootTrack.Api
      
    - name: Test with dotnet
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/FootTrack.Api
      
  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps: 
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: docker build -t back .
    - name: Tags
      run: |
        docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
        docker tag back ${{ secrets.DOCKER_USER }}/back:latest
    - name: Push
      run: |
        docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
        docker tag back ${{ secrets.DOCKER_USER }}/back:latest 
    
